### ISSUE TITLE
Update deploy.yml to restrict trigger scope

### ISSUE THREAD

**Issue by incrediblesadi** [incrediblesadi/akilahapigateway#17]
**Replace `.github/workflows/deploy.yml` with the following:**

```yaml
name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy akilahapigateway \
            --image gcr.io/akilahstack/akilahapigateway \
            --service-account 858627689875-compute@developer.gserviceaccount.com \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
```
